# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname caixa
#' @name caixa
#' @title Generate phonetic versions of strings with Caixa's method
#'
#' @description
#' The function \code{caixa} phonentically encodes the given input
#' using algorithm developed by Caixa Economica Federal.
#'
#' @param word string or vector of strings to encode
#' @param max maximum length of the resulting encodings, in characters
#'
#' @details To be inserted
#'
#' @return a character vector containing the phonetical output of
#' \code{word}, or an NA if the \code{word} value is NA
#'
#' @family utilsIPEA
#'
#' @examples
#' caixa("")
#' caixa(c("school", "benji"))
#'
#' @useDynLib utilsIPEA
#' @importFrom Rcpp evalCpp
#' @export
caixa_ <- function(word, max = 20L) {
    .Call('utilsIPEA_caixa_', PACKAGE = 'utilsIPEA', word, max)
}

